name: replace-in-files
files:
  - 'src/**/*.js'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /monkey-tpls-description/g
    to: Assist download Bilibili YouTube via yt‑dlp command.
  - item: ${PROJECT_NAME}
